global using System;
global using System.Collections.Generic;
global using System.IO;
global using System.Linq;
global using System.Threading;
global using System.Threading.Tasks;
global using AndroidWidget.Core.Abstractions;
global using AndroidWidget.Core.Devices;
global using AndroidWidget.Core.Files;
global using AndroidWidget.Core.Messaging;
global using AndroidWidget.Core.Operations;
global using AndroidWidget.Core.Settings;
global using DragEventArgs = System.Windows.DragEventArgs;
global using MouseEventArgs = System.Windows.Input.MouseEventArgs;
global using Point = System.Windows.Point;
